create table songs
(
    id          bigint generated by default as identity
        primary key,
    resource_id bigint,
    album       varchar(255),
    artist      varchar(255),
    length      varchar(255),
    name        varchar(255),
    year        varchar(255)
);